apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      labels:
        app: order-processing
    spec:
      containers:
        - name: order-processing
          image: yourusername/order-processing:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: microservices-config
            - secretRef:
                name: microservices-secrets
